---
apiVersion: v1
kind: Service
metadata:
  name: java2pod
  labels:
    app: java2pod
spec:
  type: NodePort
  selector:
    app: java2pod
  ports:
    - protocol: TCP
      port: 8080
      name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java2pod
spec:
  selector:
    matchLabels:
      app: java2pod
  replicas: 1
  template:
    metadata:
      labels:
        app: java2pod
    spec:
      containers:
        - name: java2pod
          image: quay.io/gresch/java2pod-extended:1.0.0-SNAPSHOT
          ports:
            - containerPort: 8080
